import type { Metadata } from "next";
import "./globals.css";
import TopBar from "@/components/common/TopBar/TopBar";
import NavigationBar from "@/components/common/NavigationBar/NavigationBar";
import StartStudyButton from "@/components/common/StartStudyButton/StartStudyButton";
import LayoutMainContent from "./LayoutMainContent";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <LayoutMainContent child={children}/>
      </body>
    </html>
  );
}
